### ISSUE TITLE
@zuvaai/document-viewer not found

### ISSUE THREAD

**Issue by syatom** [zuvaai/docai-examples#4]
When installing the dependencies @zuvaai/document-viewer is not found. How can I install this so that I can carrying on with the example provided?
`npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@zuvaai%2fdocument-viewer - Not found
npm ERR! 404 
npm ERR! 404  '@zuvaai/document-viewer@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.`

**Comment by matt-cote** [comment]
Hi @syatom, we have updated the visibility of the package so that it is now public.

You will also need to update your `.npmrc` file to be able to install packages from our organization, eg.

```
//npm.pkg.github.com/:_authToken=TOKEN
@zuvaai:registry=https://npm.pkg.github.com/
```

You can find more info about this in the [GitHub Packages documentation](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry#installing-packages-from-other-organizations)

Hope that helps!

**Comment by syatom** [comment]
In your example you have "@zuvaai/document-viewer": "0.0.1" in the package.json as a dependency but I cannot get it to install. Can you provide an example on how to get this package installed.

**Comment by matt-cote** [comment]
> In your example you have "@zuvaai/document-viewer": "0.0.1" in the package.json as a dependency but I cannot get it to install. Can you provide an example on how to get this package installed.

We've added more detailed steps to the tutorial regarding how to create a personal access token and set up the `.npmrc` file in order to be able to install this dependency from GitHub Packages.

https://zuva.ai/documentation/tutorials/displaying-documents/#requirements-1

**Comment by syatom** [comment]
Thanks have managed to get it installed now following the updated documentation.
